// AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Pelicula } from 'src/app/models/pelicula';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  @Input() pelicula: Pelicula;
  @Output() MarcarFavorita = new EventEmitter;

  constructor() { }

  ngOnInit(): void {
  }

  seleccionar(event, pelicula) {
    this. MarcarFavorita.emit({
      pelicula: pelicula
    });
  }

}

<article class="article-item">
    <div class="image-wrap">
        <img src="{{pelicula.image}}" alt="{{pelicula.title}}">
    </div>

    <h2>{{pelicula.title}}</h2>
    <span class="year" [ngClass]='{
                    "year-green": pelicula.year > 2016,
                    "year-red": pelicula.year < 2016
                }'>

        {{pelicula.year}}
    </span>
    <a href="article.html">Leer más</a>
    <button (click)="seleccionar($event, $pelicula)">
        Seleccionar como favorita
    </button>
    <div class="clearfix"></div>
</article>

// AprendiendoVue/src/components/Pelicula.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img
        :src="pelicula.image"
        :alt="pelicula.title"
        :title="pelicula.title"
      />
    </div>

    <h2>{{ pelicula.title }}</h2>
    <span
      class="date"
      :class="{
        yeargreen: pelicula.year >= 2015,
        yearred: pelicula.year < 2015,
      }"
    >
      {{ pelicula.year }}
    </span>
    <a href="article.html">Leer más</a>
    <input
      type="button"
      value="Marcar como favorita"
      @click="pasarFavoritaAlPadre(pelicula)"
    />
    <div class="clearfix"></div>
  </article>
</template>

<script>
export default {
  name: "Pelicula",
  props: ["pelicula"],
  methods: {
    pasarFavoritaAlPadre(pelicula) {
      this.$emit('favorita', pelicula);
    },
  },
};
</script>
